<?php
namespace Orolyn\Collection;

use Ds\Set;
use SplObjectStorage;

/**
 * @template T
 * @extends HashSet<T>
 */
class OrderedSet extends HashSet
{
    private bool $dirty = true;

    /**
     * @inheritDoc
     */
    public function getIterator(): \Generator
    {
        $this->sort();

        parent::getIterator(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function add(mixed $item): void
    {
        $this->dirty = true;

        parent::add($item); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function copy(): HashSet
    {
        $this->sort();

        return parent::copy(); // TODO: Change the autogenerated stub
    }

    private function sort()
    {
        if ($this->dirty) {
            $this->source->sort();
            $this->dirty = false;
        }
    }
}
